### ISSUE TITLE
FINUFFT.jl fails to run (yet) on Julia 1.7.1 / macOS arm64

### ISSUE THREAD

**Issue by radiobed** [ludvigak/FINUFFT.jl#36] opened 2022-01-03 00:36 UTC
Hi,

Due I guess to how recent the Julia release has been (22/12), I cannot get FINUFFT to run in that setup. I get:
```
ERROR: LoadError: UndefVarError: libfinufft not defined
```
when trying "using FINUFFT".

I looked into it but couldn't see an obvious, easy, fix. libfinufft was not created. When I run it on Julia 1.6.x under the rosetta emulator for M1, it runs properly (and there is a libfinufft.so etc.) My guess is libfinunfft has no support so far for that architecture.

If you'd have time to get have a look that would be great. Thanks again for creating the package!

Cheers,
Paul.

**Comment by ahbarnett** [comment] 2022-01-03 22:51
Hello Paul,
To test this I just downloaded julia 1.7.1 on glibc 64bit linux, and `pkg> add FINUFFT` then `julia> using FINUFFT` works fine.

Pasting the example code from the README.md works with the first (default opts) call, but now fails with a new (to me) issue when trying nondefault opts:

```
julia> fk_fftord = nufft1d1(x, c, 1, tol, ms, debug=1, modeord=1, nthreads=4)
ERROR: MethodError: no method matching nufft1d1(::Vector{Float64}, ::Vector{ComplexF64}, ::Int64, ::Float64, ::Int64; debug=1, modeord=1, nthreads=4)
Closest candidates are:
  nufft1d1(::Array{Float64}, ::Array{ComplexF64}, ::Integer, ::Float64, ::Integer) at ~/.julia/packages/FINUFFT/EEFSZ/src/FINUFFT.jl:249 got unsupported keyword arguments "debug", "modeord", "nthreads"
  nufft1d1(::Array{Float64}, ::Array{ComplexF64}, ::Integer, ::Float64, ::Integer, ::nufft_opts) at ~/.julia/packages/FINUFFT/EEFSZ/src/FINUFFT.jl:249 got unsupported keyword arguments "debug", "modeord", "nthreads"
Stacktrace:
 [1] top-level scope
   @ REPL[12]:1
```
So I will ask @lulibin for help on this one.

So, firstly see if you can get to this stage. Are you sure you copied your Project.toml over to v1.7 and did 'pkg> update'
?
Best, Alex

**Comment by ahbarnett** [comment] 2022-01-03 23:00
I just confirmed all tests work on v1.6.3 but break on v1.7.1.
It seems to be that the methods (functions) are not seen when they use optional kwargs.

Here is the error output:

```
julia> cd("SCDA/nufft/FINUFFT.jl/test")
julia> include("runtests.jl")
[ Info: Testing error handling
setup_spreader warning: increasing tol=1e-100 to eps_mach=1.1e-16.
setup_spreader warning: at upsampfac=2, tol=1.1e-16 would need kernel width ns=17; clipping to max 16.
┌ Warning: requested tolerance epsilon too small to achieve
└ @ FINUFFT ~/.julia/packages/FINUFFT/EEFSZ/src/FINUFFT.jl:202
Error handling and dumb inputs: Error During Test at /home/alex/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:30
  Test threw exception
  Expression: e.errno == FINUFFT.ERR_MAXNALLOC
  type MethodError has no field errno
  Stacktrace:
   [1] getproperty(x::MethodError, f::Symbol)
     @ Base ./Base.jl:42
   [2] macro expansion
     @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
   [3] macro expansion
     @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:30 [inlined]
   [4] macro expansion
     @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
   [5] top-level scope
     @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:6
  
  caused by: MethodError: no method matching nufft1d1(::Vector{Float64}, ::Vector{ComplexF64}, ::Int64, ::Float64, ::Int64; spread_kerevalmeth=0, upsampfac=9.007199254740992e15)
  Closest candidates are:
    nufft1d1(::Array{Float64}, ::Array{ComplexF64}, ::Integer, ::Float64, ::Integer) at ~/.julia/packages/FINUFFT/EEFSZ/src/FINUFFT.jl:249 got unsupported keyword arguments "spread_kerevalmeth", "upsampfac"
    nufft1d1(::Array{Float64}, ::Array{ComplexF64}, ::Integer, ::Float64, ::Integer, ::nufft_opts) at ~/.julia/packages/FINUFFT/EEFSZ/src/FINUFFT.jl:249 got unsupported keyword arguments "spread_kerevalmeth", "upsampfac"
  Stacktrace:
   [1] macro expansion
     @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:28 [inlined]
   [2] macro expansion
     @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
   [3] top-level scope
     @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:6
Error handling and dumb inputs: Error During Test at /home/alex/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:39
  Test threw exception
  Expression: e.errno == FINUFFT.ERR_UPSAMPFAC_TOO_SMALL
  type MethodError has no field errno
  Stacktrace:
   [1] getproperty(x::MethodError, f::Symbol)
     @ Base ./Base.jl:42
   [2] macro expansion
     @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
   [3] macro expansion
     @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:39 [inlined]
   [4] macro expansion
     @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
   [5] top-level scope
     @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:6
  
  caused by: MethodError: no method matching nufft1d1(::Vector{Float64}, ::Vector{ComplexF64}, ::Int64, ::Float64, ::Int64; spread_kerevalmeth=0, upsampfac=0.9)
  Closest candidates are:
    nufft1d1(::Array{Float64}, ::Array{ComplexF64}, ::Integer, ::Float64, ::Integer) at ~/.julia/packages/FINUFFT/EEFSZ/src/FINUFFT.jl:249 got unsupported keyword arguments "spread_kerevalmeth", "upsampfac"
    nufft1d1(::Array{Float64}, ::Array{ComplexF64}, ::Integer, ::Float64, ::Integer, ::nufft_opts) at ~/.julia/packages/FINUFFT/EEFSZ/src/FINUFFT.jl:249 got unsupported keyword arguments "spread_kerevalmeth", "upsampfac"
  Stacktrace:
   [1] macro expansion
     @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:37 [inlined]
   [2] macro expansion
     @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
   [3] top-level scope
     @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:6
Error handling and dumb inputs: Error During Test at /home/alex/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:47
  Test threw exception
  Expression: e.errno == FINUFFT.HORNER_WRONG_BETA
  type MethodError has no field errno
  Stacktrace:
   [1] getproperty(x::MethodError, f::Symbol)
     @ Base ./Base.jl:42
   [2] macro expansion
     @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:445 [inlined]
   [3] macro expansion
     @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:47 [inlined]
   [4] macro expansion
     @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
   [5] top-level scope
     @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:6
  
  caused by: MethodError: no method matching nufft1d1(::Vector{Float64}, ::Vector{ComplexF64}, ::Int64, ::Float64, ::Int64; upsampfac=1.5)
  Closest candidates are:
    nufft1d1(::Array{Float64}, ::Array{ComplexF64}, ::Integer, ::Float64, ::Integer) at ~/.julia/packages/FINUFFT/EEFSZ/src/FINUFFT.jl:249 got unsupported keyword argument "upsampfac"
    nufft1d1(::Array{Float64}, ::Array{ComplexF64}, ::Integer, ::Float64, ::Integer, ::nufft_opts) at ~/.julia/packages/FINUFFT/EEFSZ/src/FINUFFT.jl:249 got unsupported keyword argument "upsampfac"
  Stacktrace:
   [1] macro expansion
     @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:45 [inlined]
   [2] macro expansion
     @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
   [3] top-level scope
     @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:6
Error handling and dumb inputs: Error During Test at /home/alex/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:4
  Got exception outside of a @test
  UndefVarError: finufft_makeplan not defined
  Stacktrace:
    [1] macro expansion
      @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:51 [inlined]
    [2] macro expansion
      @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
    [3] top-level scope
      @ ~/SCDA/nufft/FINUFFT.jl/test/test_error_handler.jl:6
    [4] include(fname::String)
      @ Base.MainInclude ./client.jl:451
    [5] macro expansion
      @ ~/SCDA/nufft/FINUFFT.jl/test/runtests.jl:4 [inlined]
    [6] macro expansion
      @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
    [7] top-level scope
      @ ~/SCDA/nufft/FINUFFT.jl/test/runtests.jl:4
    [8] include(fname::String)
      @ Base.MainInclude ./client.jl:451
    [9] top-level scope
      @ REPL[26]:1
   [10] eval
      @ ./boot.jl:373 [inlined]
   [11] eval_user_input(ast::Any, backend::REPL.REPLBackend)
      @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:150
   [12] repl_backend_loop(backend::REPL.REPLBackend)
      @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:244
   [13] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
      @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:229
   [14] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
      @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:362
   [15] run_repl(repl::REPL.AbstractREPL, consumer::Any)
      @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:349
   [16] (::Base.var"#930#932"{Bool, Bool, Bool})(REPL::Module)
      @ Base ./client.jl:394
   [17] #invokelatest#2
      @ ./essentials.jl:716 [inlined]
   [18] invokelatest
      @ ./essentials.jl:714 [inlined]
   [19] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
      @ Base ./client.jl:379
   [20] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:309
   [21] _start()
      @ Base ./client.jl:495
FINUFFT: Error During Test at /home/alex/SCDA/nufft/FINUFFT.jl/test/runtests.jl:3
  Got exception outside of a @test
  LoadError: UndefVarError: finufftReal not defined
  Stacktrace:
    [1] test_nufft(tol::Float64, dtype::DataType)
      @ Main ~/SCDA/nufft/FINUFFT.jl/test/test_nufft.jl:11
    [2] top-level scope
      @ ~/SCDA/nufft/FINUFFT.jl/test/test_nufft.jl:252
    [3] include(fname::String)
      @ Base.MainInclude ./client.jl:451
    [4] macro expansion
      @ ~/SCDA/nufft/FINUFFT.jl/test/runtests.jl:5 [inlined]
    [5] macro expansion
      @ ~/julia-1.7.1/share/julia/stdlib/v1.7/Test/src/Test.jl:1283 [inlined]
    [6] top-level scope
      @ ~/SCDA/nufft/FINUFFT.jl/test/runtests.jl:4
    [7] include(fname::String)
      @ Base.MainInclude ./client.jl:451
    [8] top-level scope
      @ REPL[26]:1
    [9] eval
      @ ./boot.jl:373 [inlined]
   [10] eval_user_input(ast::Any, backend::REPL.REPLBackend)
      @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:150
   [11] repl_backend_loop(backend::REPL.REPLBackend)
      @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:244
   [12] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
      @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:229
   [13] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
      @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:362
   [14] run_repl(repl::REPL.AbstractREPL, consumer::Any)
      @ REPL ~/julia-1.7.1/share/julia/stdlib/v1.7/REPL/src/REPL.jl:349
   [15] (::Base.var"#930#932"{Bool, Bool, Bool})(REPL::Module)
      @ Base ./client.jl:394
   [16] #invokelatest#2
      @ ./essentials.jl:716 [inlined]
   [17] invokelatest
      @ ./essentials.jl:714 [inlined]
   [18] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
      @ Base ./client.jl:379
   [19] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:309
   [20] _start()
      @ Base ./client.jl:495
  in expression starting at /home/alex/SCDA/nufft/FINUFFT.jl/test/test_nufft.jl:252
Test Summary:                    | Error  Total
FINUFFT                          |     5      5
  Error handling and dumb inputs |     4      4
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 5 errored, 0 broken.
in expression starting at /home/alex/SCDA/nufft/FINUFFT.jl/test/runtests.jl:3
```

A mystery since julia is not supposed to break backwd compat! Help is needed... Thanks, Alex

**Comment by ahbarnett** [comment] 2022-01-03 23:21
Here's a simpler demo of failure:

```
julia> FINUFFT.BIGINT
Int64

julia> FINUFFT.finufftReal
ERROR: UndefVarError: finufftReal not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base ./Base.jl:35
 [2] top-level scope
   @ REPL[12]:1


```

**Comment by ludvigak** [comment] 2022-01-04 14:42
I'm also surprised that things have broken between Julia versions, so that v.2.1.0 is no longer working. However, part of what you're seeing @ahbarnett is because we have forgotten to tag a new release since the last round of updates.

On my Linux computer, I just got everything to work with Julia 1.7.1 by installing the master:
```
]add FINUFFT#master
```

@radiobed see if this works for you in the meantime, while we tag a new release

**Comment by lulibin** [comment] 2022-01-04 15:07
‘add FINUFFT#master’ works on my Mac and Linux. Yes, I think we need to tag
the latest version so that the Julia Registry get updated, thanks.

**Comment by ahbarnett** [comment] 2022-01-05 21:12
Dear Paul,
If you `add FINUFFT#master` it has been updated just now. Please let us know if works for you.

**Comment by ludvigak** [comment] 2022-01-06 19:39
Latest code is now released as v3.0, so simply updating the package should help

**Comment by radiobed** [comment] 2022-01-07 22:40
Thanks so much Alex! I’ll try it as soon as I get back from holiday in a week.
________________________________

**Comment by ludvigak** [comment] 2022-02-02 10:49
@radiobed did you resolve this?

**Comment by radiobed** [comment] 2022-02-09 04:58
Thanks for asking Ludvig and Alex -- sorry for the delay in coming back. I recompiled and tested finally, and low and behold, it works perfectly!! 

Thanks again for FINUFFT. I'll drop a line to say how we are using it in radio astronomy once my package is published in a few months.

Paul.

**Closed** 2022-02-09 06:43 UTC
